services:
  vn2vn-speech2text:
    container_name: vn2vn-speech2text
    image: vn2vn-speech2text
    build:
      context: ./src/services/speech2text
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./data:/audios
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
