services:
  speech2text:
    container_name: speech2text
    image: speech2text
    build:
      context: ./src/services/speech2text
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - /home/dominux/Downloads/6d0d5ffe-cccc-4268-8858-6518c0fa85ca:/audios
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
